
# Publish all joint states -----------------------------------
position_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
  gains:
    panda_joint1: {p: 600.0,  i: 10.0, d: 50.0}
    panda_joint2: {p: 600.0,  i: 10.0, d: 50.0}
    panda_joint3: {p: 600.0,  i: 10.0, d: 50.0}
    panda_joint4: {p: 600.0,  i: 10.0, d: 20.0}
    panda_joint5: {p: 250.0,  i: 10.0, d: 20.0}
    panda_joint6: {p: 150.0,  i: 1.0, d: 20.0}
    panda_joint7: {p: 50.0,  i: 10.0, d: 10.0}

panda_simulator:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100


  # Panda SDK Controllers: Position --------------------------
  effort_joint_position_controller:
    type: panda_sim_controllers/PandaPositionController
    topic_joint_command: /panda_simulator/motion_controller/arm/joint_commands
    topic_set_speed_ratio: /panda_simulator/arm/set_speed_ratio
    joints:
      panda_joint1_controller:
        joint: panda_joint1
        pid: {p: 600.0,  i: 10.0, d: 50.0}
      panda_joint2_controller:
        joint: panda_joint2
        pid: {p: 600.0,  i: 10.0, d: 50.0}
      panda_joint3_controller:
        joint: panda_joint3
        pid: {p: 600.0,  i: 10.0, d: 50.0}
      panda_joint4_controller:
        joint: panda_joint4
        pid: {p: 600.0,  i: 10.0, d: 20.0}
      panda_joint5_controller:
        joint: panda_joint5
        pid: {p: 250.0,  i: 10.0, d: 20.0}
      panda_joint6_controller:
        joint: panda_joint6
        pid: {p: 150.0,  i: 1.0, d: 20.0}
      panda_joint7_controller:
        joint: panda_joint7
        pid: {p: 50.0,  i: 10.0, d: 10.0}
        
  # Panda SDK Controllers: Velocity --------------------------
  effort_joint_velocity_controller:
    type: panda_sim_controllers/PandaVelocityController
    topic: /panda_simulator/motion_controller/arm/joint_commands
    joints:
      panda_joint1_controller:
        joint: panda_joint1
        pid: {p: 10,  i: 0.0, d: 0.1}
      panda_joint2_controller:
        joint: panda_joint2
        pid: {p: 100,  i: 1.0, d: 0.1}
      panda_joint3_controller:
        joint: panda_joint3
        pid: {p: 0.05,  i: 0.0, d: 0.01}
      panda_joint4_controller:
        joint: panda_joint4
        pid: {p: 0.5,  i: 0.01, d: 0.1}
      panda_joint5_controller:
        joint: panda_joint5
        pid: {p: 1.0,  i: 0.0, d: 0.01}
      panda_joint6_controller:
        joint: panda_joint6
        pid: {p: 0.05,  i: 0.0, d: 0.01}
      panda_joint7_controller:
        joint: panda_joint7
        pid: {p: 0.05,  i: 0.0, d: 0.01}

  # Panda SDK Controllers: Effort --------------------------
  effort_joint_torque_controller:
    type: panda_sim_controllers/PandaEffortController
    topic: /panda_simulator/motion_controller/arm/joint_commands
    joints:
      panda_joint1_controller:
        joint: panda_joint1
      panda_joint2_controller:
        joint: panda_joint2
      panda_joint3_controller:
        joint: panda_joint3
      panda_joint4_controller:
        joint: panda_joint4
      panda_joint5_controller:
        joint: panda_joint5
      panda_joint6_controller:
        joint: panda_joint6
      panda_joint7_controller:
        joint: panda_joint7

  # Panda SDK Controllers: Gravity Compensation ------------
  effort_joint_gravity_controller:
    type: panda_sim_controllers/PandaGravityController
    command_topic: /panda_simulator/arm/gravity_compensation_torques
    disable_topic: /panda_simulator/arm/suppress_gravity_compensation
    disable_timeout: 0.2
    joints:
      panda_joint1_controller:
        joint: panda_joint1
      panda_joint2_controller:
        joint: panda_joint2
      panda_joint3_controller:
        joint: panda_joint3
      panda_joint4_controller:
        joint: panda_joint4
      panda_joint5_controller:
        joint: panda_joint5
      panda_joint6_controller:
        joint: panda_joint6
      panda_joint7_controller:
        joint: panda_joint7

